#
# for kubernetes-dashboard
#
{{- if .Values.k8dashboard.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "common.names.fullname" . }}-crbind
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.k8dashboard.serviceAccount.name }}
  namespace: {{ include "common.names.namespace" . }}
{{- end }}