apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-dbcon
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: kafka-dbcon
spec:
  ports:
  - protocol: TCP
    port: 8083
    targetPort: connector
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-dbcon