{{- if .Values.test.enabled }}
{{ $full_name := include "common.names.fullname" . }}
{{ $labels := (include "common.labels.standard" . ) }}
{{ $matchLabels := (include "common.labels.matchLabels" . ) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $full_name }}-test-srccon
  labels: 
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: kafka-test-srccon
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8083
    targetPort: connector
  selector: 
    {{- $matchLabels | nindent 4 }}
    app.kubernetes.io/component: kafka-test-srccon
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $full_name }}-test-sinkcon
  labels: 
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: kafka-test-sinkcon
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8083
    targetPort: connector
  selector: 
    {{- $matchLabels | nindent 4 }}
    app.kubernetes.io/component: kafka-test-sinkcon
{{- end }}