{{ $full_name := include "common.names.fullname" . }}
{{- if .Values.init.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $full_name }}-init-{{ .Release.Revision }}
spec:
  template:
    spec:
      {{- if .Values.init.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.init.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ $full_name }}-init
        image: {{ .Values.init.container.image }}:{{ .Values.init.container.tag }}
        {{- if .Values.init.container.pullPolicy }}
        imagePullPolicy: {{ .Values.init.container.pullPolicy | default "IfNotPresent" }}
        {{- end }}
        command: ["/bin/sh", "-c", "{{ join " && " .Values.init.commands }}"]
        volumeMounts:
      {{- range $k, $v := .Values.init.files }}
      - name: {{ $full_name }}-init-cmd
        mountPath: /usr/local/bin/{{ $k }}
        subPath: {{ $k }}
      {{- end }}
      {{- if and .Values.kafka_connect.enabled (not .Values.test.enabled) }}
        {{- range $cnt := .Values.kafka_connect.connects }}
        {{- $cfg_name := printf "%s-connector-%s" $full_name $cnt.type }}
        {{- /* 전체 등록 스크립트 */}}
        - name: {{ $cfg_name }}
          mountPath: /usr/local/bin/{{ $full_name }}-{{ $cnt.type }}-all.sh
          subPath: {{ $full_name }}-{{ $cnt.type }}-all.sh
        {{- /* 커넥트 대기 스크립트 */}}
        - name: {{ $cfg_name }}
          mountPath: /usr/local/bin/{{ $cnt.type }}-wait-connect.sh
          subPath: {{ $cnt.type }}-wait-connect.sh
        {{- range $grp := $cnt.connector_groups }}
        {{- range $con := $grp.connectors }}
        {{- $cname := include "connector.filename" (dict "cnt_type" $cnt.type "grp_name" $grp.name "con_name" $con.name ) }}
        - name: {{ $cfg_name }}
          mountPath: /usr/local/bin/{{ $cname }}
          subPath: {{ $cname }}
        {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
      volumes:
      - name: {{ $full_name }}-init-cmd
        configMap:
          name: {{ $full_name }}-init-cmd
          defaultMode: 0777
      {{- if and .Values.kafka_connect.enabled (not .Values.test.enabled) }}
        {{- range $cnt := .Values.kafka_connect.connects }}
        {{- $cfg_name := printf "%s-connector-%s" $full_name $cnt.type }}
      - name: {{ $cfg_name }}
        configMap:
          name: {{ $cfg_name }}
          defaultMode: 0777
        {{- end }}
      {{- end }}
      restartPolicy: Never
  backoffLimit: 1
{{- end }}