{{ $full_name := include "common.names.fullname" . }}
{{ $rel_name := .Release.Name }}
{{ $rev := .Release.Revision }}
{{- with .Values.test }}
{{- if .enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $full_name }}-test-{{ $rev }}
  labels: 
    app.kubernetes.io/component: test
    app.kubernetes.io/instance: {{ $rel_name }}
spec:
  template:
    spec:
      containers:
      - name: {{ $full_name }}-test
        image: {{ .container.image }}:{{ .container.tag }}
        {{- if .container.pullPolicy }}
        imagePullPolicy: {{ .container.pullPolicy | default "IfNotPresent" }}
        {{- end }}
        command: ["/bin/sh", "-c", "init_mysql.sh && jdbcsrc_reg_mysql.sh && wait-ksqldb.sh && run_test.sh"]
        volumeMounts:
        - name: {{ $full_name }}-test-cmd
          mountPath: /usr/local/bin/init_mysql.sh
          subPath: init_mysql.sh
        - name: {{ $full_name }}-test-cmd
          mountPath: /usr/local/bin/jdbcsrc_reg_mysql.sh
          subPath: jdbcsrc_reg_mysql.sh
        - name: {{ $full_name }}-test-cmd
          mountPath: /usr/local/bin/wait-ksqldb.sh
          subPath: wait-ksqldb.sh          
        - name: {{ $full_name }}-test-cmd
          mountPath: /usr/local/bin/run_test.sh
          subPath: run_test.sh
        - name: {{ $full_name }}-test-code
          mountPath: /tests
      volumes:
        - name: {{ $full_name }}-test-cmd
          configMap:
            name: {{ $full_name }}-test-cmd
            defaultMode: 0777
        - name: {{ $full_name }}-test-code
          configMap:
            name: {{ $full_name }}-test-code
      restartPolicy: Never
  backoffLimit: 0
{{- end }}
{{- end }}