{{- if .Values.init.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: test-init
spec:
  template:
    spec:
      containers:
      - name: init
        image: {{ .Values.init.container.image }}:{{ .Values.init.container.tag }}
        {{- if .Values.init.container.pullPolicy }}
        imagePullPolicy: {{ .Values.init.container.pullPolicy | default "IfNotPresent" }}
        {{- end }}
        command: ["/bin/sh", "-c", "{{ join " && " .Values.init.commands }}"]
        volumeMounts:
        {{- range $k, $v := .Values.init.files }}
        - name: test-init-cmd
          mountPath: /usr/local/bin/{{ $k }}
          subPath: {{ $k }}
        {{- end }}
      volumes:
        - name: test-init-cmd
          configMap:
            name: {{ include "common.names.fullname" . }}-test-init-cmd
            defaultMode: 0777
      restartPolicy: Never
  backoffLimit: 1
{{- end }}