{{ $full_name := include "common.names.fullname" . }}
{{ $rel_name := .Release.Name }}
{{ $rev := .Release.Revision }}
{{- with .Values.test }}
{{- if .enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $full_name }}-test-run-{{ $rev }}
  labels: 
    app.kubernetes.io/component: test
    app.kubernetes.io/instance: {{ $rel_name }}
spec:
  template:
    metadata:
    spec:
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ $full_name }}-test
        image: {{ .container.image }}:{{ .container.tag }}
        {{- if .container.pullPolicy }}
        imagePullPolicy: {{ .container.pullPolicy | default "IfNotPresent" }}
        {{- end }}
        env:
        {{- range $ev := .envs }}
        - name: {{ $ev.name }}
          value: {{ $ev.value }} 
        {{- end }}
        command: ["/bin/sh", "-c", "rm_s3dir.sh && init_mysql.sh && srccon_reg_mysql.sh && wait_ksqldb.sh && run_test.sh"]
        volumeMounts:
        - name: {{ $full_name }}-test-cmd
          mountPath: /usr/local/bin/init_mysql.sh
          subPath: init_mysql.sh
        - name: {{ $full_name }}-test-cmd
          mountPath: /usr/local/bin/srccon_reg_mysql.sh
          subPath: srccon_reg_mysql.sh
        - name: {{ $full_name }}-test-cmd
          mountPath: /usr/local/bin/sinkcon_reg_mysql.sh
          subPath: sinkcon_reg_mysql.sh
        - name: {{ $full_name }}-test-cmd
          mountPath: /usr/local/bin/wait_ksqldb.sh
          subPath: wait_ksqldb.sh          
        - name: {{ $full_name }}-test-cmd
          mountPath: /usr/local/bin/rm_s3dir.sh
          subPath: rm_s3dir.sh          
        - name: {{ $full_name }}-test-cmd
          mountPath: /usr/local/bin/run_test.sh
          subPath: run_test.sh
        - name: {{ $full_name }}-test-code
          mountPath: /tests
      volumes:
        - name: {{ $full_name }}-test-cmd
          configMap:
            name: {{ $full_name }}-test-cmd
            defaultMode: 0777
        - name: {{ $full_name }}-test-code
          configMap:
            name: {{ $full_name }}-test-code
      restartPolicy: Never
  backoffLimit: 0
{{- end }}
{{- end }}