{{- if and .Values.ingress .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alpaka-ingress
  annotations:
  {{- if .Values.vendor }}
    {{- if eq .Values.vendor "k3d" }}
      ingress.kubernetes.io/ssl-redirect: false
    {{- else if eq .Values.vendor "aws" }}
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
    {{- end }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
      {{- if and .Values.grafana .Values.grafana.enabled }}
        - path: /
          pathType: Prefix
          backend: 
            service:
              name: full-grafana
              port: 
                number: 3000 
      {{- end -}}
{{- end -}}