{{/*
    유저 커넥터 설정은 test.enabled=false 일때만 동작 
*/}}
{{- if and .Values.kafka_connect.enabled (not .Values.test.enabled) }}
{{ $full_name := include "common.names.fullname" . }}
{{ $rel_name := .Release.Name }}
{{- range $cnt := .Values.kafka_connect.connects }}
{{- $cnt_url := printf "http://%s-connect-%s:8083" $full_name $cnt.type }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $full_name }}-connector-{{ $cnt.type }}
data:
  {{ $cnt.type }}-wait-connect.sh: |
    # 커넥트가 준비될 때까지 대기 
    until $(curl --output /dev/null --silent --head --fail {{ $cnt_url }}); do
        echo "waiting for Kafka connect '{{$cnt.type}}' to activate."
        sleep 5
    done 
{{- $cmds := list (printf "%s-wait-connect.sh" $cnt.type ) }}
{{- range $grp := $cnt.connector_groups }}
{{- range $con := $grp.connectors }}
  {{- $cname := include "connector.filename" (dict "cnt_type" $cnt.type "grp_name" $grp.name "con_name" $con.name ) }}
  {{ $cname }}: |
    echo '> run {{ $cname }}'
    {{- $cvals := $cnt.values | default (dict) }}
    {{- $gvals := $grp.values | default (dict) }}
    {{- $common := $grp.common | default (dict) }}
    {{- $cfg := .config | default (dict) }}
    {{- include "connector.register" ( dict "global" $ "cnt_url" $cnt_url "cvals" $cvals "gvals" $gvals "com" $common "cname" $cname "cfg" $cfg ) }}
  {{- $cmds = append $cmds $cname }}
{{- end }}
{{- end }}
  {{ $full_name }}-{{ $cnt.type }}-all.sh: | 
{{ join "\n" $cmds | indent 4 }}
{{- end }}
{{- end }}