{{- if .Values.init.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-init-cmd
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.init.files }}
    {{ $k }}: |
      {{ $v | indent 6 | trim }}
  {{- end }}
#   {{ $db_type := .Values.dbcon.config.db.type }}
#   reg_conn.sh: |
#     sleep 10 &&
#     curl -X POST http://localhost:8083/connectors -H "Content-Type: application/json" -d '{
#         "name": "jdbc_source_{{ .Values.dbcon.config.db.type }}",
#         "config": {
#             {{- with .Values.dbcon.config }}
#                 "mode": "{{ .mode }}",
#                 {{- with .db }}
#                     "connection.url": "jdbc:{{ .type }}://{{ .addr }}:{{ .port }}/{{ .name }}?serverTimezone={{ .timezone }}",
#                     "connection.user": "{{ .user }}",
#                     "connection.password": "{{ .password }}",
#                 {{- end }}
#                 {{-  with .auto }}
#                 "auto.create": {{ .create }},
#                 "auto.evolve": {{ .evolve }},
#                 {{- end }}
#                 {{- with .poll }}
#                     "poll.interval.ms": {{ .interval_ms | default 5000 }},
#                 {{- end }}
#                 {{- with .offset }}
#                     {{- with .flush }}
#                         "offset.flush.interval.ms": {{ .interval_ms | default 60000 }},
#                     {{- end }}
#                 {{- end }}
#                 {{- with .delete }}
#                     {{- if .enabled }}
#                         "delete.enabled": {{ .enabled }},
#                     {{- end }}
#                 {{- end }}
#                 {{- with .isolation }}
#                     "transaction.isolation.mode": "{{ .mode | default "READ_UNCOMMITTED" }}",
#                 {{- end }}
#                 {{- with .topic }}
#                     "topic.prefix": "{{ .prefix | default (printf "%s-" $db_type) }}",
#                 {{- end }}
#                 {{- with .batch }}
#                     "batch.max.rows": {{ .max_rows | default 1000 }},
#                 {{- end }}
#                 {{- with .tasks }}
#                     "tasks.max": {{ .max | default 1 }},
#                 {{- end }}
#                 {{- with .timestamp }}
#                     "timestamp.inclusive": {{ .inclusive | default false }},
#                     {{- with .deplay }}
#                         "timestamp.delay.interval.ms": {{ .interval_ms | default 0 }},
#                     {{- end }}
#                 {{- end }}
#                 {{- with .key }}
#                     "key.converter": "{{ .converter | default "org.apache.kafka.connect.storage.StringConverter" }}",
#                 {{- end }}
#                 {{- with .value }}
#                     "value.converter": "{{ .converter | default "org.apache.kafka.connect.json.JsonConverter" }}",
#                     {{- with .converter }}
#                         {{- with .schemas  }}
#                             "value.converter.schemas.enable": {{ .enable | default false }},
#                         {{- end }}
#                     {{- end }}
#                 {{- end }}
#                 {{- with .table }}
#                     {{- if .whitelist }}
#                         "table.whitelist": {{ .whitelist }},
#                     {{- end }}
#                 {{- end }}
#                 {{- with .timestamp }}
#                     {{- with .column }}
#                         "timestamp.column.name": {{ .name }}
#                     {{- end }}
#                 {{- end }}
#                 {{- if .query }}
#                 "query": {{ .query }}
#                 {{- end }}
#                 {{- with .transforms }}
#                     {{- with .copyFieldToKey }}
#                         "type": "{{ .type | default "org.apache.kafka.connect.transforms.ValueToKey" }}"
#                         "fields": {{ .fields }}
#                     {{- end }}
#                     {{- with .extractKeyFromStruct }}
#                         "type": "{{ .type | default "org.apache.kafka.connect.transforms.ExtractField$Key" }}"
#                         "fields": {{ .fields }}
#                     {{- end }}
#                 {{- end }}
#             {{- end }}
#             "connector.class" : "io.confluent.connect.jdbc.JdbcSourceConnector"
#         }
#     }'
{{- end }}