{{ $full_name := include "common.names.fullname" . }}
{{ $rel_name := .Release.Name }}
{{ $broker := printf "%s-kafka-headless:9092" .Release.Name }}
{{- with .Values.test }}
{{- if .enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $full_name }}-test-code
data:
  test_kafka.py: |
    from subprocess import run 

    def kafka_topics(cmds):
        out = run(['kafka-topics.sh', '--bootstrap-server={{ $broker }}'] + cmds, capture_output=True)
        assert out.returncode == 0
        return out.stdout.decode()

    def test_topic_list():
        """기본 토픽 나열."""
        ret = kafka_topics(["--list"])
        ans = set([
            '__consumer_offsets', 
            'connect-configs', 
            'connect-offsets', 
            'connect-status']) 
        com = ans & set(ret.split('\n'))
        assert len(com) == 4

  test_etc.py: |
    import urllib
    from urllib.request import urlopen

    def test_grafana():
        """그라파나 접속 테스트."""
        url = 'http://{{ $rel_name }}-grafana:3000'
        urlopen(url)

    def test_kafkaui():
        """UI for Kafka 접속 테스트."""
        url = 'http://{{ $rel_name }}-kafka-ui:80'
        urlopen(url)

    def test_prometheus():
        """프로메테우스 접속 테스트."""
        url = 'http://{{ $rel_name }}-prometheus-prometheus:9090'
        urlopen(url)

    def test_k8dashboard():
        """쿠버네티스 대쉬보드 접속 테스트."""
        url = 'https://{{ $rel_name }}-k8dashboard:8443'
        try:
            urlopen(url)
        except urllib.error.URLError as e:
            if 'CERTIFICATE_VERIFY_FAILED' not in str(e):
                raise e
{{- end }}
{{- end }}