{{/* 
  유저 커넥트 디플로이는 test.enabled=false 일때만
*/}}
{{- if and .Values.kafka_connect.enabled (not .Values.test.enabled) }}
{{ $fullname := include "common.names.fullname" . }}
{{ $labels := include "common.labels.standard" . }}
{{ $matchLabels := include "common.labels.matchLabels" . }}
{{- range $cnt := .Values.kafka_connect.connects -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}-{{ $cnt.type }}
  labels: 
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: kafka-{{ $cnt.type }}
spec:
  replicas: {{ $cnt.replicaCount | default 1 }}
  selector:
    matchLabels: 
      {{- $matchLabels | nindent 6 }}
      app.kubernetes.io/component: kafka-{{ $cnt.type }}
  template:
    metadata:
      labels: {{ $labels | nindent 8 }}
        app.kubernetes.io/component: kafka-{{ $cnt.type }}
    spec:
      {{- if .Values.kafka_connect.nodeSelector }}
      nodeSelector:
        {{- toYaml $cnt.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ $cnt.type }}-connect
        image: {{ $cnt.container.image }}:{{ $cnt.container.tag }}
        imagePullPolicy: {{ $cnt.container.pullPolicy | default "IfNotPresent" }}
        command: ['/opt/bitnami/kafka/bin/connect-distributed.sh']
        args: ['/opt/bitnami/kafka/config/connect-distributed.properties']
        env:
          - name: TZ
            value: {{ $cnt.timezone | default "UTC" }}
        ports:
          - name: connector
            containerPort: 8083
        volumeMounts:
          - name: conn-cfg
            mountPath: /opt/bitnami/kafka/config
      volumes:
        - name: conn-cfg
          configMap:
            name: {{ $fullname }}-{{ $cnt.type }}-cfg
{{- end }}
{{- end }}
