{{/* 
  테스트 커넥트 디플로이는 test.enabled=true 일때만
*/}}
{{- if .Values.test.enabled }}
{{ $fullname := include "common.names.fullname" . }}
{{ $labels := include "common.labels.standard" . }}
{{ $matchLabels := include "common.labels.matchLabels" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}-test-srccon
  labels: 
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: kafka-test-srccon
spec:
  replicas: {{ .Values.test.replicaCount | default 1 }}
  selector:
    matchLabels: 
      {{- $matchLabels | nindent 6 }}
      app.kubernetes.io/component: kafka-test-srccon
  template:
    metadata:
      labels: {{ $labels | nindent 8 }}
        app.kubernetes.io/component: kafka-test-srccon
    spec:
      containers:
      - name: test-srccon-connect
        image: {{ .Values.test.connects.srccon.container.image }}:{{ .Values.test.connects.srccon.container.tag }}
        imagePullPolicy: {{ .Values.test.connects.srccon.container.pullPolicy | default "IfNotPresent" }}
        command: ['/opt/bitnami/kafka/bin/connect-distributed.sh']
        args: ['/opt/bitnami/kafka/config/connect-distributed.properties']
        env:
        - name: TZ
          value: {{ .Values.test.timezone | default "UTC" }}
        {{- range $ev := .Values.test.envs }}
        - name: {{ $ev.name }}
          value: {{ $ev.value }} 
        {{- end }}
        ports:
          - name: connector
            containerPort: 8083
        volumeMounts:
          - name: conn-cfg
            mountPath: /opt/bitnami/kafka/config
      {{- with .Values.test.connects.srccon.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: conn-cfg
          configMap:
            name: {{ $fullname }}-test-srccon-cfg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}-test-sinkcon
  labels: 
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: kafka-test-sinkcon
spec:
  replicas: {{ .Values.test.replicaCount | default 1 }}
  selector:
    matchLabels: 
      {{- $matchLabels | nindent 6 }}
      app.kubernetes.io/component: kafka-test-sinkcon
  template:
    metadata:
      labels: {{ $labels | nindent 8 }}
        app.kubernetes.io/component: kafka-test-sinkcon
    spec:
      containers:
      - name: test-sinkcon-connect
        image: {{ .Values.test.connects.sinkcon.container.image }}:{{ .Values.test.connects.sinkcon.container.tag }}
        imagePullPolicy: {{ .Values.test.connects.sinkcon.container.pullPolicy | default "IfNotPresent" }}
        command: ['/opt/bitnami/kafka/bin/connect-distributed.sh']
        args: ['/opt/bitnami/kafka/config/connect-distributed.properties']
        env:
        - name: TZ
          value: {{ .Values.test.timezone | default "UTC" }}
        {{- range $ev := .Values.test.envs }}
        - name: {{ $ev.name }}
          value: {{ $ev.value }} 
        {{- end }}
        ports:
          - name: connector
            containerPort: 8083
        volumeMounts:
          - name: conn-cfg
            mountPath: /opt/bitnami/kafka/config
      {{- with .Values.test.connects.sinkcon.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: conn-cfg
          configMap:
            name: {{ $fullname }}-test-sinkcon-cfg
{{- end }}