{{/* 
  테스트 커넥트 디플로이는 test.enabled=true 일때만
*/}}
{{- if .Values.test.enabled }}
{{ $fullname := include "common.names.fullname" . }}
{{ $labels := include "common.labels.standard" . }}
{{ $matchLabels := include "common.labels.matchLabels" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}-connect-test-jdbcsrc
  labels: 
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: kafka-connect-test-jdbcsrc
spec:
  replicas: {{ .Values.test.replicaCount | default 1 }}
  selector:
    matchLabels: 
      {{- $matchLabels | nindent 6 }}
      app.kubernetes.io/component: kafka-connect-test-jdbcsrc
  template:
    metadata:
      labels: {{ $labels | nindent 8 }}
        app.kubernetes.io/component: kafka-connect-test-jdbcsrc
    spec:
      containers:
      - name: test-jdbcsrc-connect
        image: {{ .Values.test.connect.container.image }}:{{ .Values.test.connect.container.tag }}
        imagePullPolicy: {{ .Values.test.connect.container.pullPolicy | default "IfNotPresent" }}
        command: ['/opt/bitnami/kafka/bin/connect-distributed.sh']
        args: ['/opt/bitnami/kafka/config/connect-distributed.properties']
        env:
          - name: TZ
            value: {{ .Values.test.timezone | default "UTC" }}
        ports:
          - name: connector
            containerPort: 8083
        volumeMounts:
          - name: conn-cfg
            mountPath: /opt/bitnami/kafka/config
      volumes:
        - name: conn-cfg
          configMap:
            name: {{ $fullname }}-connect-test-jdbcsrc-cfg
{{- end }}