{{- if .Values.tool.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-tool
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.tool.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 -}}
      {{- end }}
      labels:
        {{- include "common.labels.standard" . | nindent 8 -}}
        {{- if .Values.tool.podLabels -}}
        {{ toYaml .Values.tool.podLabels | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: alpaka-tool
    spec:
      containers:
      - name: alpaka-tool
        image: "{{ .Values.tool.image.repository }}:{{ .Values.tool.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.tool.image.pullPolicy }}
        resources:
          {{- toYaml .Values.tool.resources | nindent 12 }}
        command: ['sleep']
        args: ['infinity']
      {{- if .Values.tool.dnsPolicy }}
      dnsPolicy: {{ .Values.tool.dnsPolicy }}
      {{- end }}
      {{- if .Values.tool.dnsConfig }}                                                                         
      dnsConfig: {{- include "common.tplvalues.render" (dict "value" .Values.tool.dnsConfig "context" $) | nindent 8 }}
      {{- end }}
      {{- with .Values.tool.nodeSelector -}}
      nodeSelector:
        {{- toYaml . | nindent 8 -}}
      {{- end -}}
      {{- with .Values.tool.affinity -}}
      affinity:
        {{- toYaml . | nindent 8 -}}
      {{- end -}}
      {{- with .Values.tool.tolerations -}}
      tolerations:
        {{- toYaml . | nindent 8 -}}
      {{- end -}}
{{- end -}}
