#
#  AWS EKS 설정 템플릿 (이것을 복사해서 커스터마이징)
#
# - 여기에 없는 설정은 values.yaml 을 참고
# - RELEASE 는 배포명으로 대체
#
k8s_dist: eks

ui4kafka:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: public
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8080}]'
  yamlApplicationConfig:
    kafka:
      clusters:
        - name: RELEASE-kafka
          bootstrapServers: RELEASE-kafka-headless:9092
          zookeeper: RELEASE-zookeeper-headless:2181
          kafkaConnect:
            - name: srccon
              address: http://RELEASE-alpaka-srccon:8083
          metrics:
            port: 5556
            type: JMX

prometheus:
  prometheus:
    ingress:
      enabled: true
      hostname: "*"
      path: /*
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/group.name: public
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 9090}]'
    additionalScrapeConfigs:
      internal:
        jobList:
        - job_name: kminion-metrics
          static_configs:
          - targets:
            - RELEASE-kminion:8080
        - job_name: zookeeper
          static_configs:
          - targets:
            - RELEASE-zookeeper-metrics:9141

grafana:
  ingress:
    enabled: true
    hostname: "*"
    path: /*
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: public
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 3000}]'
  datasources:
    secretDefinition:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://RELEASE-prometheus-prometheus:9090
        isDefault: true
  dashboardsConfigMaps:
    - configMapName: RELEASE-alpaka-grafana-cluster
      fileName: kminion-cluster_rev1.json
    - configMapName: RELEASE-alpaka-grafana-topic
      fileName: kminion-topic_rev1.json
    - configMapName: RELEASE-alpaka-grafana-groups
      fileName: kminion-groups_rev1.json
    - configMapName: RELEASE-alpaka-grafana-zookeeper
      fileName: zookeeper-by-prometheus_rev4.json
    - configMapName: RELEASE-alpaka-grafana-jvm
      fileName: altassian-overview_rev1.json


kminion:
  kminion:
    config:
      kafka:
        brokers: ["RELEASE-kafka-headless:9092"]
    exporter:
      host: "RELEASE-kminion"


k8dashboard:
  ingress:
    enabled: true
    # k8dashboard Helm 차트의 버그로 커스텀패스 이용
    customPaths:
    - path: /*
      pathType: ImplementationSpecific
      backend:
        service:
          name: RELEASE-k8dashboard
          port:
            number: 8443
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: public
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8443}]'


ingress:
  enabled: false