#
#  k3d 설정 템플릿 (이것을 복사해서 커스터마이징)
#
# - 여기에 없는 설정은 values.yaml 을 참고
# - RELEASE 는 배포명으로 대체
# - k3d 의 경우 멀티 노드로 가정하고 Node Selector 부여 (사용하지 않으면 제거)
#

k8s_dist: k3d


kafka:
  nodeSelector:
    alpaka/node-type: worker
  zookeeper:
    nodeSelector:
      alpaka/node-type: worker
  metrics:
    kafka:
      nodeSelector:
        alpaka/node-type: worker


ui4kafka:
  nodeSelector:
    alpaka/node-type: infra
  yamlApplicationConfig:
    kafka:
      clusters:
        - name: RELEASE-kafka
          bootstrapServers: RELEASE-kafka-headless:9092
          zookeeper: RELEASE-zookeeper-headless:2181
          kafkaConnect:
            - name: srccon
              address: http://RELEASE-alpaka-srccon:8083
          metrics:
            port: 5556
            type: JMX

prometheus:
  prometheus:
    nodeSelector:
      alpaka/node-type: infra
    additionalScrapeConfigs:
      internal:
        jobList:
        - job_name: kminion-metrics
          static_configs:
          - targets:
            - RELEASE-kminion:8080
        - job_name: zookeeper
          static_configs:
          - targets:
            - RELEASE-zookeeper-metrics:9141
  operator:
    nodeSelector:
      alpaka/node-type: infra
  alertmanager:
    nodeSelector:
      alpaka/node-type: infra
  blackboxExporter:
    nodeSelector:
      alpaka/node-type: infra

grafana:
  grafana:
    nodeSelector:
      alpaka/node-type: infra
  datasources:
    secretDefinition:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://RELEASE-prometheus-prometheus:9090
        isDefault: true
  dashboardsConfigMaps:
    - configMapName: RELEASE-alpaka-grafana-cluster
      fileName: kminion-cluster_rev1.json
    - configMapName: RELEASE-alpaka-grafana-topic
      fileName: kminion-topic_rev1.json
    - configMapName: RELEASE-alpaka-grafana-groups
      fileName: kminion-groups_rev1.json
    - configMapName: RELEASE-alpaka-grafana-zookeeper
      fileName: zookeeper-by-prometheus_rev4.json
    - configMapName: RELEASE-alpaka-grafana-jvm
      fileName: altassian-overview_rev1.json


kminion:
  nodeSelector:
    alpaka/node-type: infra
  kminion:
    config:
      kafka:
        brokers: ["RELEASE-kafka-headless:9092"]
    exporter:
      host: "RELEASE-kminion"


k8dashboard:
  nodeSelector:
    alpaka/node-type: infra


ingress:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"


kafka_connect:
  connects: []
  # 소스 커넥트
  # - type: srccon 
  #   nodeSelector: 
  #     alpaka/node-type: worker


ksqldb:
  nodeSelector:
    alpaka/node-type: infra


init: 
  nodeSelector:
    alpaka/node-type: worker


tool:
  nodeSelector: 
    alpaka/node-type: infra


test: 
  nodeSelector:
    alpaka/node-type: worker
  connects: 
    # 소스 커넥터 노드
    srccon:
      nodeSelector:
        alpaka/node-type: worker
    # 싱크 커넥터 노드
    sinkcon:
      nodeSelector:
        alpaka/node-type: worker
