#
#  minikube 설정 템플릿 (이것을 복사해서 커스터마이징)
#
# - 여기에 없는 설정은 values.yaml 을 참고
# - RELEASE 는 배포명으로 대체
#
k8s_dist: minikube

ui4kafka:
  yamlApplicationConfig:
    kafka:
      clusters:
        - name: RELEASE-kafka
          bootstrapServers: RELEASE-kafka-headless:9092
          zookeeper: RELEASE-zookeeper-headless:2181
          kafkaConnect:
            - name: srccon
              address: http://RELEASE-alpaka-srccon:8083
          metrics:
            port: 5556
            type: JMX

prometheus:
  prometheus:
    additionalScrapeConfigs:
      internal:
        jobList:
        - job_name: kminion-metrics
          static_configs:
          - targets:
            - RELEASE-kminion:8080
        - job_name: zookeeper
          static_configs:
          - targets:
            - RELEASE-zookeeper-metrics:9141

grafana:
  datasources:
    secretDefinition:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://RELEASE-prometheus-prometheus:9090
        isDefault: true
      ## 그라파나 로키 사용시 
      # - name: Loki
      #   type: loki
      #   access: proxy
      #   url: http://RELEASE-loki-gateway
      # jsonData:
      #   maxLines: 1000
  dashboardsConfigMaps:
    - configMapName: RELEASE-alpaka-grafana-cluster
      fileName: kminion-cluster_rev1.json
    - configMapName: RELEASE-alpaka-grafana-topic
      fileName: kminion-topic_rev1.json
    - configMapName: RELEASE-alpaka-grafana-groups
      fileName: kminion-groups_rev1.json
    - configMapName: RELEASE-alpaka-grafana-zookeeper
      fileName: zookeeper-by-prometheus_rev4.json
    - configMapName: RELEASE-alpaka-grafana-jvm
      fileName: altassian-overview_rev1.json


kminion:
  kminion:
    config:
      kafka:
        brokers: ["RELEASE-kafka-headless:9092"]
    exporter:
      host: "RELEASE-kminion"


## 그라파나 로키 사용시 
# loki:
#   enabled: true
#   retention_period: 48h


ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /


ksqldb:
  ksqldb:
    nameOverride: RELEASE-ksqldb
    kafka:
      bootstrapServer: PLAINTEXT://RELEASE-kafka-headless:9092