#
# 리눅스에서 k3s 사용시
#

# 프로메테우스 설정
prometheus:
  prometheus:
    additionalScrapeConfigs:
      internal:
        jobList:
        - job_name: kminion-metrics
          static_configs:
          - targets:
            - mkb-kminion:8080
        - job_name: zookeeper
          static_configs:
          - targets:
            - mkb-zookeeper-metrics:9141

grafana:
  dashboardsConfigMaps:
    - configMapName: mkb-alpaka-grafana-cluster
      fileName: kminion-cluster_rev1.json
    - configMapName: mkb-alpaka-grafana-topic
      fileName: kminion-topic_rev1.json
    - configMapName: mkb-alpaka-grafana-groups
      fileName: kminion-groups_rev1.json
    - configMapName: mkb-alpaka-grafana-zookeeper
      fileName: zookeeper-by-prometheus_rev4.json
    - configMapName: mkb-alpaka-grafana-jvm
      fileName: altassian-overview_rev1.json


kminion:
  kminion:
    config:
      kafka:
        brokers: ["mkb-kafka-headless:9092"]
    exporter:
      host: "mkb-kminion"


ingress:
  annotations:
    # k3s (k3d) 설치용
    kubernetes.io/ingress.class: "traefik"
