#
# 리눅스에서 minikube 사용시
#

ui4kafka:
  ingress:
    enabled: true 
    host: ui4kafka.alpaka.wai
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /

k8dashboard:
  ingress:
    enabled: true 
    hosts: 
    - k8dashboard.alpaka.wai
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /

prometheus:
  prometheus:
    ingress:
      enabled: true 
      hostname: prometheus.alpaka.wai
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    additionalScrapeConfigs:
      internal:
        jobList:
        - job_name: kminion-metrics
          static_configs:
          - targets:
            - k3s-kminion:8080
        - job_name: zookeeper
          static_configs:
          - targets:
            - k3s-zookeeper-metrics:9141

grafana:
  ingress:
    enabled: true 
    hostname: grafana.alpaka.wai
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
  dashboardsConfigMaps:
    - configMapName: k3s-alpaka-grafana-cluster
      fileName: kminion-cluster_rev1.json
    - configMapName: k3s-alpaka-grafana-topic
      fileName: kminion-topic_rev1.json
    - configMapName: k3s-alpaka-grafana-groups
      fileName: kminion-groups_rev1.json
    - configMapName: k3s-alpaka-grafana-zookeeper
      fileName: zookeeper-by-prometheus_rev4.json
    - configMapName: k3s-alpaka-grafana-jvm
      fileName: altassian-overview_rev1.json


kminion:
  kminion:
    config:
      kafka:
        brokers: ["k3s-kafka-headless:9092"]
    exporter:
      host: "k3s-kminion"
