#
#  minikube 사용시
#

k8s_dist: minikube

ui4kafka:
  yamlApplicationConfig:
    kafka:
      clusters:
        - name: mkb-kafka
          bootstrapServers: mkb-kafka-headless:9092
          zookeeper: mkb-zookeeper-headless:2181
          kafkaConnect:
            - name: dbcon
              address: http://mkb-alpaka-dbcon:8083
          metrics:
            port: 5556
            type: JMX

prometheus:
  prometheus:
    additionalScrapeConfigs:
      internal:
        jobList:
        - job_name: kminion-metrics
          static_configs:
          - targets:
            - mkb-kminion:8080
        - job_name: zookeeper
          static_configs:
          - targets:
            - mkb-zookeeper-metrics:9141

grafana:
  datasources:
    secretDefinition:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://mkb-prometheus-prometheus:9090
        isDefault: true
  dashboardsConfigMaps:
    - configMapName: mkb-alpaka-grafana-cluster
      fileName: kminion-cluster_rev1.json
    - configMapName: mkb-alpaka-grafana-topic
      fileName: kminion-topic_rev1.json
    - configMapName: mkb-alpaka-grafana-groups
      fileName: kminion-groups_rev1.json
    - configMapName: mkb-alpaka-grafana-zookeeper
      fileName: zookeeper-by-prometheus_rev4.json
    - configMapName: mkb-alpaka-grafana-jvm
      fileName: altassian-overview_rev1.json


kminion:
  kminion:
    config:
      kafka:
        brokers: ["mkb-kafka-headless:9092"]
    exporter:
      host: "mkb-kminion"


ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
