#
# WSL 에서 minikube 사용시 (Ingress 사용 않음)
#
use_ingress: false

# 프로메테우스 설정
prometheus:
  prometheus:
    additionalScrapeConfigs:
      internal:
        jobList:
        - job_name: kminion-metrics
          static_configs:
          - targets:
            - wslmkb-kminion:8080
        - job_name: zookeeper
          static_configs:
          - targets:
            - wslmkb-zookeeper-metrics:9141

grafana:
  dashboardsConfigMaps:
    - configMapName: wslmkb-alpaka-grafana-cluster
      fileName: kminion-cluster_rev1.json
    - configMapName: wslmkb-alpaka-grafana-topic
      fileName: kminion-topic_rev1.json
    - configMapName: wslmkb-alpaka-grafana-groups
      fileName: kminion-groups_rev1.json
    - configMapName: wslmkb-alpaka-grafana-zookeeper
      fileName: zookeeper-by-prometheus_rev4.json
    - configMapName: wslmkb-alpaka-grafana-jvm
      fileName: altassian-overview_rev1.json


kminion:
  kminion:
    config:
      kafka:
        brokers: ["wslmkb-kafka-headless:9092"]
    exporter:
      host: "wslmkb-kminion"
