apiVersion: v2
name: alpaka
description: Yet another Kafka deployment chart.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "3.3.1"

dependencies:
  - name: kafka
    version: 19.1.x
    repository: https://charts.bitnami.com/bitnami
  - name: kube-prometheus
    version: 8.3.x
    # repository: https://charts.bitnami.com/bitnami
    # Ingress 에 '*' 가 hostname 으로 지정될 때 버그 수정 (https://github.com/bitnami/charts/issues/14070)
    repository: https://raw.githubusercontent.com/haje01/bitnami-charts/master/bitnami/kube-prometheus
    alias: prometheus
    condition: prometheus.enabled
  - name: grafana
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: grafana.enabled
  - name: kminion
    version: 0.10.x
    # policy/v1beta 의 호환성 문제
    repository: https://raw.githubusercontent.com/haje01/kminion/master/charts/patched
    condition: grafana.enabled
  - name: kubernetes-dashboard
    version: 5.x.x
    repository: https://kubernetes.github.io/dashboard/
    alias: k8dashboard
    condition: k8dashboard.enabled
  - name: kafka-ui
    version: 0.4.x
    repository:  https://raw.githubusercontent.com/haje01/kafka-ui/master/charts/kafka-ui
    condition: kafka-ui.enabled
