#
# 밸류 파일 내 값은 기본 값으로 동작 
# 

# 쿠버네티스 배포판 이름 (minibkue, k3s, k3d, eks 중 하나)
k8s_dist: UNKNOWN

# 주의: RELEASE 가들어간 이름은 설치용 설정 파일에서 배포 이름으로 대체되어야함.

# 카프카 설정
kafka:
  replicaCount: 1
  defaultReplicationFactor: 1
  numPartitions: 8
  ## 노드 리소스 조건
  # resources:
  #   requests:
  #     cpu: "2700m"
  #     memory: "10Gi"
  #   limits:
  #     cpu: "3600m"
  #     memory: "14Gi"

  metrics:
    kafka:
      enabled: true
    jmx:
      enabled: true
    serviceMonitor:
      enabled: true
      relabelings:
        - sourceLabels: ["container", "pod"]
          regex: "jmx-exporter;"
          replacement: jmx
          targetLabel: job
        # 인스턴스 값을 IP 가 아닌 Pod 명으로 
        - regex: "instance"
          action: labeldrop
        - sourceLabels: ["pod"]
          targetLabel: instance
      metricRelabelings:
        # 인스턴스 값을 IP 가 아닌 Pod 명으로 
        - regex: "instance"
          action: labeldrop
        - sourceLabels: ["pod"]
          targetLabel: instance

  zookeeper:
    enabled: true
    replicaCount: 1
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 10s
        scrapeTimeout:  5s
        relabelings: 
          - replacement: zookeeper
            targetLabel: job
          # 인스턴스 값을 IP 가 아닌 Pod 명으로 
          - regex: "instance"
            action: labeldrop
          - sourceLabels: ["pod"]
            targetLabel: instance
        metricRelabelings:
          # 인스턴스 값을 IP 가 아닌 Pod 명으로 
          - regex: "instance"
            action: labeldrop
          - sourceLabels: ["pod"]
            targetLabel: instance

  deleteTopicEnable: true
  podLabels:
    job: kafka


# 프로메테우스 설정
prometheus:
  enabled: true
  prometheus:
    enabled: true
    additionalScrapeConfigs:
      enabled: true
      type: internal
      internal:
        jobList:
        - job_name: kminion-metrics
          scrape_interval: 10s
          scrape_timeout:  5s
          metrics_path: "/metrics"
          static_configs:
          - targets:
            - RELEASE-kminion:8080
        - job_name: zookeeper
          scrape_interval: 10s
          scrape_timeout:  5s
          metrics_path: "/metrics"
          static_configs:
          - targets:
            - RELEASE-zookeeper-metrics:9141


# 쿠버네티스 대쉬보드 설정
k8dashboard:
  enabled: true
  protocolHttp: true 
  service:
    externalPort: 8443
  serviceAccount:
    name: k8dash-admin
  extraArgs:
    - --token-ttl=86400
    - --enable-skip-login 
    - --enable-insecure-login
  tolerations:
  - key: type
    operator: "Equal"
    value: "ctrl"
    effect: "NoSchedule"


# 알파카 Tool 설정
tool:
  enabled: true
  name: alpaka-tool
  podLabels: {}
  podAnnotations: {}
  container:
    image: "haje01/alpaka-tool"
    tag: latest
    pullPolicy: IfNotPresent
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  dnsConfig:
    # 필요시 외부 DNS 등록 
    # nameservers:
    #   - 213.234.76.4
    options:
      - name: ndots
        value: "2"


# 카프카 DB 관련 커넥터 설정
dbcon:
  enabled: true
  replicaCount: 1
  kafkaClientPort: 9092
  container:
    image: "haje01/kafka-dbcon"
    tag: latest
    pullPolicy: IfNotPresent
  timezone: Asia/Seoul


# UI for 카프카 설정
ui4kafka:
  enabled: true
  yamlApplicationConfig:
    kafka:
      clusters:
        - name: RELEASE-kafka
          bootstrapServers: RELEASE-kafka-headless:9092
          zookeeper: RELEASE-zookeeper-headless:2181
          kafkaConnect:
            - name: dbcon
              address: http://RELEASE-alpaka-dbcon:8083
          metrics:
            port: 5556
            type: JMX
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false
  tolerations:
  - key: type
    operator: "Equal"
    value: "ctrl"
    effect: "NoSchedule"


# 그라파나 설정
grafana:
  enabled: true
  adminSecretName: mkb-grafana-admin
  admin:
    user: admin
    password: admindjemals
  datasources:
    secretDefinition:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://mkb-prometheus-prometheus:9090
          isDefault: true
  dashboardsProvider:
    enabled: true
  dashboardsConfigMaps:
    - configMapName: RELEASE-alpaka-grafana-cluster
      fileName: kminion-cluster_rev1.json
    - configMapName: RELEASE-alpaka-grafana-topic
      fileName: kminion-topic_rev1.json
    - configMapName: RELEASE-alpaka-grafana-groups
      fileName: kminion-groups_rev1.json
    - configMapName: RELEASE-alpaka-grafana-zookeeper
      fileName: zookeeper-by-prometheus_rev4.json
    - configMapName: RELEASE-alpaka-grafana-jvm
      fileName: altassian-overview_rev1.json


# 그라파나용 KMinion 대쉬보드 설정
kminion:
  enabled: true
  kminion:
    config:
      kafka:
        brokers: ["RELEASE-kafka-headless:9092"]

    exporter:
      host: "RELEASE-kminion"
      port: 8080

  service:
    annotations:
      prometheus.io/probe: kminion


# 공용 ingress 설정
ingress:
  enabled: true
  hostname: "alpaka.web"
  annotations:
    # # minikube 설치용
    # nginx.ingress.kubernetes.io/rewrite-target: /$1

    # # K3S (K3D) 설치용
    # kubernetes.io/ingress.class: traefik

    # # AWS EKS 설치용
    # kubernetes.io/ingress.class: alb
    # alb.ingress.kubernetes.io/group.name: public
    # alb.ingress.kubernetes.io/scheme: internet-facing
    # alb.ingress.kubernetes.io/target-type: ip
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 9090}]'


#
# 초기화 
#
# 설치 후 초기화에 필요한 명령을 정의하고 실행한다.
# 
init: 
  enabled: false 


#
#  테스트 관련
#

#
# 테스트용 MySQL 정보
#
# MySQL 은 test.enabled 가 true 인 경우만 설치된다.
#
mysql:
  auth:
    password: mypass
    rootPassword: mypass

# 테스트
test:
  enabled: true
  container:
    image: "haje01/alpaka-tool"
    tag: 0.0.1
    pullPolicy: IfNotPresent
